config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
  devise_for :admins
  devise_scope :admin do
    post '/admins/sign_as_demo' => 'admins/sessions#sign_as_demo'
    get '/admins/sign_out' => 'devise/sessions#destroy'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: redirect('/home')

  get 'home', to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'admin_index', to: 'articles#admin_index'
  get '/404', to: 'errors#not_found'
  get '/406', to: 'errors#unacceptable'
  get '/500', to: 'errors#internal_server'
  get '/422', to: 'errors#unprocessable'
  resources :articles
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :recoverable, :registerable, :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ActiveRecord::Base
  has_one_attached :photo

  validates :title, presence: true, length: { minimum: 3, maximum: 100}
  validates :body, presence:true
end

app/controllers/admins/sessions_controller.rb
# frozen_string_literal: true

class Admins::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  def sign_as_demo
    @demo_user ||= Admin.find_by_email('admin@interdelima.com')
    if current_admin.nil?
      sign_in(@demo_user)
      redirect_to admin_index_path, notice: 'Signed in as demo user.'
    end
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :show, :destroy]
  before_action :authenticate_admin!, only: [:admin_index, :new, :create, :edit,:update, :destroy]

  def admin_index
    @articles = Article.all
  end

  def index
    @articles = Article.order(created_at: :desc)
  end

  def show
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      flash[:notice] = "Artículo creado exitosamente"
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "El Artículo fue actualizado"
      redirect_to article_path(@article)
    else
      flash[:notice] = "El Artículo no fue actualizado"
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    flash[:notice] = "Artículo eliminado"
    redirect_to admin_index_path
  end

  private
    def article_params
      params.require(:article).permit(:title, :body, :photo)
    end

    def set_article
      @article = Article.find(params[:id])
    end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def not_found
    render status: 404
  end

  def internal_server
    render status: 500
  end

  def unprocessable
    render status: 422
  end

  def unacceptable
    render status: 406
  end
end

app/controllers/graphql_controller.rb
# frozen_string_literal: true

class GraphqlController < ApplicationController
  # If accessing from outside this domain, nullify the session
  # This allows for outside API access while preventing CSRF attacks,
  # but you'll have to authenticate your user separately
  # protect_from_forgery with: :null_session

  def execute
    variables = prepare_variables(params[:variables])
    query = params[:query]
    operation_name = params[:operationName]
    context = {
      # Query context goes here, for example:
      # current_user: current_user,
    }
    result = InterLimaSchema.execute(query, variables: variables, context: context, operation_name: operation_name)
    render json: result
  rescue StandardError => e
    raise e unless Rails.env.development?
    handle_error_in_development(e)
  end

  private

  # Handle variables in form data, JSON body, or a blank value
  def prepare_variables(variables_param)
    case variables_param
    when String
      if variables_param.present?
        JSON.parse(variables_param) || {}
      else
        {}
      end
    when Hash
      variables_param
    when ActionController::Parameters
      variables_param.to_unsafe_hash # GraphQL-Ruby will validate name and type of incoming variables.
    when nil
      {}
    else
      raise ArgumentError, "Unexpected parameter: #{variables_param}"
    end
  end

  def handle_error_in_development(e)
    logger.error e.message
    logger.error e.backtrace.join("\n")

    render json: { errors: [{ message: e.message, backtrace: e.backtrace }], data: {} }, status: 500
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal:true

# Manage the different pages of the website
class PagesController < ApplicationController
  def home
    @banner_articles = Article.all.reverse
  end

  def about; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/flash_helper.rb
module FlashHelper
    def css_class_for_flash(flash_key)
        case flash_key.to_sym
        when :error
            "bg-red-100 text-red-700"
        else
            "bg-blue-100 text-blue-700"
        end
    end
end

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
 <h2>The following errors prevented the article from saving:</h2>
 <ul>
 <% @article.errors.full_messages.each do |msg|%>
 <li><%= msg %></li>
 <% end %>
 </ul>
<% end %>

<div class="container mx-auto my-6 rounded border border-yellow-500 bg-black text-black">
  <div class="p-5 space-x-5 ">
    <%= form_for @article do |f| %>
    <p>
      <%= f.label :Título, class: 'text-white' %><br>
      <%= f.text_area :title, class:'text-black w-1/2 mb-5'%>
    </p>
    <p>
      <%= f.label :Cuerpo, class: 'text-white' %><br>
      <%= f.text_area :body, class:'text-black w-full'%>
    </p>
    <p class="my-6">
      <%= f.label :Imagen, class: 'text-white' %><br>
      <%= f.file_field :photo, onchange:"document.getElementById('uploaded-file').src = window.URL.createObjectURL(this.files[0])" %>
      <div class="max-w-2xl max-h-70 mx-auto mb-5" >
        <img id="uploaded-file" alt="Your image" width="100%" height="100%" />
      </div>
    </p>
    <div class="mx-auto my-6 pt-6 max-w-min">
      <%= f.submit class:'focus:outline-none bg-yellow-600 px-4 py-2 text-white rounded hover:font-bold hover:bg-yellow-500' %>
    </div>
    <% end %>
  </div>
</div>

app/views/articles/admin_index.html.erb
<div class="px-3 py-8 my-10 text-center">
  <p class="py-6 text-center font-bold text-2xl">Panel de administrador - Index de artículos</p>
  <%= link_to "Crear nuevo artículo", new_article_path, class:"my-6 mx-5 p-3 bg-yellow-500 text-lg rounded hover:font-bold hover:bg-yellow-600" %>
</div>

<div class="pb-10">
  <table class="text-center font-bold border-separate border-spacing-2">
    <tr>
      <th>Título</th>
      <th>Cuerpo</th>
      <th>Imagen</th>
      <th>Fecha</th>
      <th>Editar</th>
      <th>Mostrar</th>
      <th>Borrar</th>
    </tr>
    <% @articles.each do |article| %>
    <tr class="bg-yellow-600">
      <td class="w-1/5"><%= article.title %></td>
      <td><%= truncate article.body %></td>
      <td class="w-1/3"><% if article.photo.attached? %> <%= image_tag(article.photo, class:"h-32 inline hover:scale-150") %> <% else %>  <%= image_tag("default-placeholder.png", class: "h-32 inline hover:scale-150")%><% end %> </td>
      <td class="w-1/5"><%= local_time(article.created_at,'%e %B, %Y %l:%M%P') %></td>
      <td><%= link_to image_tag('edit.svg', class:'h-8 md:h-10 inline hover:scale-125'), edit_article_path(article) %></td>
      <td><%= link_to image_tag('show.svg', class:'h-8 md:h-10 inline hover:scale-125'), article_path(article) %></td>
      <td><%= button_to image_tag('delete.svg', class:'h-8 md:h-10 inline hover:scale-125'), article_path(article), method: :delete, data: {turbo_confirm: "¿Está seguro?"} %></td>
    </tr>
    <% end %>
  </table>
</div>

app/views/articles/edit.html.erb
<div class="flex flex-col justify-center items-center my-20 p-10">
  <p class="text-center py-6 text-xl font-bold">Editando artículo</h1>

  <%= render 'form' %>
  <%= link_to 'Regresar', :back, class:'bg-gray-300 hover:bg-gray-400 hover:font-bold text-gray-800  py-2 px-4 rounded' %>
</div>

app/views/articles/index.html.erb
<div class="px-3 py-8 my-10 text-center">
  <p class="py-4 text-center font-bold text-2xl">Mostrando todos los artículos</p>
  
  <div class="py-10 mx-auto w-1/2 ">
    <div class="flex flex-col justify-center">
        <% @articles.each do |article| %>
            <div class="m-5 shadow-lg rounded-lg border-4 border-yellow-500">
              <%= link_to article do %>
              <% if article.photo.attached? %>
                  <%= image_tag(article.photo, class:"object-fill m-0") %>
                <% else %>
                  <%= image_tag "default-placeholder.png" %>
                <% end %>
                <p class="text-center font-bold text-lg md:text-xl  bg-yellow-500 py-8"><%=article.title %></p>
              <%end%>
            </div>
        <% end %>
    </div>
  </div>
</div>

app/views/articles/new.html.erb
<div class="flex flex-col justify-center items-center my-20 p-10">
  <p class="text-center py-6 font-bold text-2xl">Creando un nuevo artículo</h1>

  <%= render 'form' %>
  <%= link_to 'Regresar', :back, class:'bg-gray-300 hover:bg-gray-400 hover:font-bold text-gray-800  py-2 px-4 rounded' %>
</div>

app/views/articles/show.html.erb
<div class="absolute h-60 max-h-80 z-[-1] w-full">
  <%=image_tag('article_background.png', class:'w-full object-cover opacity-50') %>
</div>

<div class="w-100"> 
  <%=image_tag(@article.photo, class:'mb-5 mx-auto mt-20 z-10')%>
</div>

<!--Article body-->
<div class="flex flex-col my-3 py-3">  
  <div class="flex flex-col items-center justify-center">
    <div class="max-w-xl overflow-hidden shadow-lg rounded-lg">
      <p class="text-center font-bold text-3xl py-3"><%=@article.title %></p>
      <p class="text-center text-xl py-3"><%=@article.created_at.strftime("%d %B %Y") %> - STAFF DE INTER DE LIMA</p>
    </div>
    <div class="w-1/2">
      <p class="text-left text-xl py-3"><%=@article.body %></p>
    </div>
  </div>
</div>


  <%if admin_signed_in?%>
    <%= link_to 'Regresar', admin_index_path, class:"text-center bg-yellow-600 mx-auto my-6 p-4 rounded hover:font-bold hover:bg-yellow-500"%>
  <%else%>
    <%= link_to 'Regresar', :back, class:"text-center bg-yellow-600 mx-auto my-6 p-4 rounded hover:font-bold hover:bg-yellow-500" %>
  <%end%>

app/views/layouts/_navbar.html.erb
<nav class="px-3 py-6 bg-black flex items-center justify-around relative border-b-4 border-yellow-500" data-controller="navbar"> <!--shadow md:flex md:items-center md:justify-around-->
  <!--Responsive Navbar button-->
  <div class="absolute left-3 z-100">
    <button data-action="click->navbar#toggle_sections" class="p-2 md:hidden text-white bg-white border border-transparent rounded focus:border-blue-500 focus:ring-opacity-40 focus:ring-blue-300  focus:ring dark:bg-gray-800 focus:outline-none">
        <svg xmlns="http://www.w3.org/2000/svg" class="w-4 h-4" viewBox="0 0 20 20" fill="currentColor">
            <path d="M10 6a2 2 0 110-4 2 2 0 010 4zM10 12a2 2 0 110-4 2 2 0 010 4zM10 18a2 2 0 110-4 2 2 0 010 4z" />
        </svg>
    </button>
    <!--Responsive Navbar sections-->
    <div class="hidden absolute float-right left-0 w-50 z-[1000] bg-zinc-600 text-base text-yellow-400 list-none rounded shadow my-4" id="dropdown" data-navbar-target="menu" data-action="resize@window->navbar#closeOnBigScreen">
      <li class="mx-5 text-base font-bold my-6 md:my-0">
          <a href="/home#teams" class="text-base md:text-xl hover:underline"> EQUIPOS </a>
      </li>
      <li class="mx-5 text-base font-bold my-6 md:my-0">
          <a href="/articles" class="text-x1 md:text-lg sm:text-base hover:underline"> NOTICIAS</a> <!--TO DO: add the articles/news route -->
      </li>
      <li class="mx-5 text-base font-bold my-6 md:my-0">
          <a href="/about" class="text-x1 md:text-lg sm:text-base hover:underline" > NOSOTROS</a>
      </li>
      <li class="mx-5 text-base font-bold my-6 md:my-0">
          <a href="/home#contact" class="text-x1 md:text-lg sm:text-base hover:underline"> CONTACTO</a>
      </li>
    </div>
  </div>
  
  <ul class="hidden bg-black md:flex md:items-center text-yellow-500 z-[-1] md:z-auto md:static absolute">
      <%# primary menu %>
        <li class="mx-5 text-base font-bold my-6 md:my-0">
          <a href="/home#teams" class="text-base md:text-xl hover:underline"> EQUIPOS </a>
        </li>
        <li class="mx-5 text-base font-bold my-6 md:my-0">
          <a href="/articles" class="text-x1 md:text-lg sm:text-base hover:underline"> NOTICIAS</a> <!--TO DO: add the articles/news route -->
        </li>
      </ul>

      <!--logo-->
      <div class="absolute top-1 z-10">
        <span class="cursor-pointer">
          <%= link_to image_tag('logo_oscuro.png', class:'h-28 inline md:h-32'), home_path %>
        </span>
      </div>

      <%# secondary menu %>
      <ul class="hidden bg-black md:flex md:items-center text-yellow-500 z-[-1] md:z-auto md:static absolute">
        <li class="mx-5 text-base font-bold my-6 md:my-0">
          <a href="/about" class="text-x1 md:text-lg sm:text-base hover:underline" > NOSOTROS</a>
        </li>
        <li class="mx-5 text-base font-bold my-6 md:my-0">
          <a href="/home#contact" class="text-x1 md:text-lg sm:text-base hover:underline"> CONTACTO</a>
        </li>
  </ul>


<!--Admin -->
  <%if admin_signed_in?%>
    <div class="ml-auto absolute right-5 z-1">
      <button class="flex items-center p-1" data-action="click->navbar#toggle_admin">
        <svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" class="h-8 w-8 md:h-12 md:w-12 bg-white rounded-full p-1"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"> <circle cx="12" cy="6" r="4" stroke="#000000" stroke-width="1.5"></circle> <path d="M19.9975 18C20 17.8358 20 17.669 20 17.5C20 15.0147 16.4183 13 12 13C7.58172 13 4 15.0147 4 17.5C4 19.9853 4 22 12 22C14.231 22 15.8398 21.8433 17 21.5634" stroke="#000000" stroke-width="1.5" stroke-linecap="round"></path> </g></svg>
      </button>
   
      <div class="hidden absolute float-left right-0 w-50 z-[1000] font-bold bg-zinc-600 text-base text-yellow-400 list-none divide-y divide-gray-100 rounded shadow my-4" id="dropdown" data-navbar-target="admin">
        <div class="px-4 py-3">
          <span class="block text-sm">Admin - Inter de Lima</span>
          <span class="block text-sm font-medium text-white truncate"><%= current_admin.email%></span>
        </div>
          <ul class="p-3" aria-labelledby="dropdown">
            <li>
              <%= link_to "Index de Artículos", admin_index_path, class:"hover:text-yellow-600" %>
            </li>
            <li>
              <%= link_to "Salir", destroy_admin_session_path , data: { turbo_method: :delete }, class:"hover:text-red-500" %>
            </li>
          </ul>
      </div>
    </div>
  <% else %>
    <div class="ml-auto absolute right-5 z-1">
      <%= button_to "Demo User", admins_sign_as_demo_path, class:"btn text-yellow-400 font-bold bg-zinc-600 me-2 rounded p-2" %>
    </div>
  <%end%>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Inter de Lima</title>
    <%= favicon_link_tag "logo_oscuro.png"%>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script defer src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/swiper@9/swiper-element-bundle.min.js"></script>
  </head>
  <%= render 'layouts/navbar' %>
  <!--flex col y min h screen para tener el footer siempre al final-->
  <body class="bg-neutral-900 text-white flex flex-col min-h-screen relative"> 
      <% flash.each do |name, msg| %>
        <ul data-controller="flash" class="flex items-center absolute justify-between <%= css_class_for_flash(name) %> p-4 rounded-md top-20 right-4 w-1/4 mt-5 ml-auto float mr-4 z-[1000] top-20absolute">
          <li class="mr-4"><%= msg %></li>
          <button type="button" data-action="flash#dismiss">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
            </svg>
        </button>
        </ul>
      <% end %>      
      <%= yield %>
  </body>
  <%= render 'layouts/footer' %>
</html>

app/views/pages/home.html.erb
<!--HOMEPAGE-->

<!--Social Media Sticky navbar-->

<div class="hidden lg:flex flex-col fixed right-0 top-1/4 z-50  border-4 border-yellow-500 bg-black">
    <a href="https://www.instagram.com/interdelima/" class="mx-3 my-6 px-3 py-3 space-x-3" target="_blank"> <%= image_tag("instagram.png", class:"h-16 inline hover:scale-125 transition-all duration-500 ease-out")%></a>
    <a href="https://twitter.com/interdelima" class="mx-3 my-6 px-3 py-3 space-x-3" target="_blank"> <%= image_tag("twitter.png", class:"h-16 inline hover:scale-125 transition-all duration-500 ease-out")%></a>
    <a href="https://www.youtube.com/channel/UCw1RMu-4mKd4feQxNyeHTJw" class="mx-3 my-6 px-3 py-3 space-x-3" target="_blank"> <%= image_tag("youtube.png", class:"h-16 inline hover:scale-125 transition-all duration-500 ease-out")%></a>
    <a href="https://www.tiktok.com/@interdelima?lang=es" class="mx-3 my-6 px-3 py-3 space-x-3" target="_blank"> <%= image_tag("tiktok.png", class:"h-16 inline hover:scale-125 transition-all duration-500 ease-out")%></a>
</div>


<!--Hero Section-->

<section class="py-5 bg-zinc-950"> <!--TO DO: Improve gradient or change to plain color-->

  <!--Articles Carousel-->
   <div class="py-12 mx-auto w-1/2 ">
    <swiper-container class="flex flex-col items-center justify-center " autoplay="true" pagination="true" scrollbar="true">
          <% @banner_articles.each do |article| %>
              <swiper-slide>
                <div class="max-w-full shadow-lg rounded-lg border-4 border-yellow-500">
                  <%= link_to article do %>
                  <% if article.photo.attached? %>
                    <%= image_tag(article.photo, class:"object-fill m-0") %>
                  <% else %>
                    <%= image_tag "default-placeholder.png" %>
                  <% end %>
                    <p class="text-center font-bold text-lg md:text-2xl bg-yellow-500 py-8"><%=article.title %></p>
                  <%end%>
                </div>
              </swiper-slide>
          <% end %>
    </swiper-container>
  </div>

  <!--Teams-->
  <div class="" x-data="{activeTab: 1}">
    <div id="teams" class="text-center text-2xl font-bold py-6">
      <p> NUESTROS  <span class="text-yellow-500 font-bold">EQUIPOS</span></p>
      <!--Games-->
      <div class="mx-auto my-6 py-6 inset-0 w-1/2 h-20 border-b border-yellow-500 ">
        <nav id="tabs-container" class="flex justify-center" aria-label="Tabs" role="tablist">
          <button type="button"
          class="py-3 px-3 inline-flex items-center gap-2 border border-b-0 border-yellow-500 focus:outline-none rounded-tl-md text-lg whitespace-nowrap  hover:underline"
          :class="activeTab===1 ? 'font-bold text-yellow-500 bg-yellow-500' : 'bg-zinc-600 opacity-50'"
          @click="activeTab=1"
          id="tab-1">
            <span> <%= image_tag("FIFA_logo.png", class:"max-w-sm h-8") %> </span>
          </button>
          <button type="button"
          class="py-3 px-3 inline-flex items-center gap-2 border border-b-0 border-yellow-500 focus:outline-none rounded-tr-md text-lg whitespace-nowrap hover:underline"
          :class="activeTab===2 ? 'font-bold text-yellow-500 bg-yellow-500' : 'bg-zinc-600 opacity-50'"
          @click="activeTab=2"
          id="tab-2">
            <span> <%= image_tag("Valorant_logo.png", class:"max-w-sm h-6") %> </span>
          </button>
        </nav>
      </div>
    </div>

    <div id="tabs-content" class="mt-3 mx-auto flex justify-center">
      <!--Tab-1: FIFA players-->
      <div id="tabs-content-1" x-show="activeTab===1">
        <!--Players Container-->
        <div class="md:flex items-center justify-around space-x-10">
          <!--DMS10 card-->
          <%= link_to "https://twitter.com/domenicosuarezo/with_replies", target: "_blank" do %>
            <%= image_tag("DMS10_player_card.png", class:"max-w-sm hover:scale-110 transition-all duration-500 ease-out") %>
          <% end %>
          <!--MAGIC_JS7 card-->
           <%= link_to "https://twitter.com/MagicJs7/with_replies" , target: "_blank" do %>
            <%= image_tag("MAGIC_player_card.png", class:"max-w-sm hover:scale-110 transition-all duration-500 ease-out") %>
          <% end %>
        </div>
      </div>
      <!--Tab-2: Valorant players-->
      <div id="tabs-content-2" x-show="activeTab===2" class="mx-auto w-1/2">
        <div class="relative h-0 overflow-hidden max-w-full w-full pb-96">
          <iframe class="absolute top-0 left-0 w-full h-full" src="https://www.youtube.com/embed/PW0tbayjePo" title="⚫🟡⚫ Nuevo equipo de Valorant 🔫💣 Empieza una nueva era en el Inter de Lima 🍫🍀" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
        </div>
      </div>
    </div>
  </div>

    <!--Contact Form-->

    <div id= "contact" class="text-center text-2xl font-bold my-6 py-6">
     <p> PONTE EN <span class="text-yellow-500"> CONTACTO</span> CON NOSOTROS</p>
    </div>

    <div class="text-center">
      <p class="mb-5"> Envíamos un <span class="text-yellow-500 font-bold"> mensaje</span> en cualquiera de nuestras redes:</p>
      <a href="https://www.instagram.com/interdelima/" class="" target="_blank"> <%= image_tag("instagram.png", class:"h-28 md:h-32 my-6 px-6 inline hover:scale-125 transition-all duration-500 ease-out") %> </a>
      <a href="https://www.youtube.com/channel/UCw1RMu-4mKd4feQxNyeHTJw" class="" target="_blank"> <%= image_tag("youtube.png", class:"h-28 md:h-32 my-6 px-6 inline hover:scale-125 transition-all duration-500 ease-out") %></a>
      <a href="https://www.tiktok.com/@interdelima?lang=es" class="" target="_blank"> <%= image_tag("tiktok.png", class:"h-28 md:h-32 my-6 px-6 inline hover:scale-125 transition-all duration-500 ease-out") %></a>
      <a href="https://twitter.com/interdelima" class="" target="_blank"> <%= image_tag("twitter.png", class:"h-28 md:h-32 my-6 px-6 inline hover:scale-125 transition-all duration-500 ease-out") %></a>
    </div>

  <div class="text-center text-2xl font-bold my-6 py-6">
     <p> Y ENTÉRATE DE NUESTRAS <span class="text-yellow-500"> PRÓXIMAS JUGADAS</span></p>
  </div>
</section>